### ISSUE TITLE
Support ISteamUser interface

### ISSUE THREAD

**Issue by garhow** [garhow/steam-rs#11]
The following non-publisher endpoints must be implemented:
  - [x] GetFriendList
  - [x] GetPlayerBans
  - [x] GetPlayerSummaries
  - [x] GetUserGroupList
  - [x] ResolveVanityURL

**Comment by harvey298** [comment]
Completed in #19

**Comment by garhow** [comment]
`GetPlayerBans` implemented in 787f1b2.

**Comment by garhow** [comment]
`GetUserGroupList` implemented in d050b6f.
