### ISSUE TITLE
Support ISteamRemoteStorage interface

### ISSUE THREAD

**Issue by garhow** [garhow/steam-rs#14]
The following endpoints must be implemented:
  - [ ] GetCollectionDetails
  - [ ] GetPublishedFileDetails

**Comment by garhow** [comment]
These are both POST endpoints, so we need to figure out an easy way to call POST endpoints first.

**Comment by harvey298** [comment]
I can rewrite the do_http! macro to support a JSON input

**Comment by garhow** [comment]
> I can rewrite the do_http! macro to support a JSON input

Implemented in #21

**Comment by garhow** [comment]
Completed in 694e3968d2d9aaadfe3e928a757c89dae424fa3b and d65068ffce57666eeb950e4b04b06a727b2911d8

This was done without the use of the `do_http!()` macro, though.
