### ISSUE TITLE
Support for ISteamUserAuth interface

### ISSUE THREAD

**Issue by RubberDuckShobe** [garhow/steam-rs#25]
[see documentation](https://steamapi.xpaw.me/#ISteamUserAuth)

This interface has the [AuthenticateUserTicket](https://steamapi.xpaw.me/#ISteamUserAuth/AuthenticateUserTicket) endpoint, which is absolutely *crucial* to me.

This is an example response of AuthenticateUserTicket:
```json
{
   "response":{
      "params":{
         "result":"OK",
         "steamid":"12345678901234567",
         "ownersteamid":"12345678901234567",
         "vacbanned":false,
         "publisherbanned":false
      }
   }
}
```
Like with other endpoints returning similar values, ``ownersteamid`` indicates the true owner of the app, if the app is used through family sharing.

As for the AuthenticateUser endpoint: I can't test that.

I think I could try implementing AuthenticateUserTicket myself when I have time.

**Comment by garhow** [comment]
I will look into this as soon as I can!

**Comment by garhow** [comment]
#26 has been merged. Is this ready to close?

**Comment by RubberDuckShobe** [comment]
``AuthenticateUser`` seems to be used by the Steam Client to log in. I'm not sure how to implement it, the documentation on it isn't helpful in the slightest.

**Comment by garhow** [comment]
I'm going to close this as stale until somebody can find any info on how to implement that interface.
