### ISSUE TITLE
error decoding response body: missing field `tags` at line 1 column 624

### ISSUE THREAD

**Issue by treeshateorcs** [garhow/steam-rs#35]
when trying to `steam.get_asset_prices(app_id, None, None)`

am i right in assuming this is not intentional? (rust newb here)

**Comment by treeshateorcs** [comment]
i think there's no `tags` and `tag_ids` fields

**Comment by garhow** [comment]
What AppID are you using? I can't replicate this with `440` (Team Fortress 2).

**Comment by garhow** [comment]
I think the problem may be that some apps don't return the `tags` fields. The solution may be to make the `tags` fields optional.

**Comment by treeshateorcs** [comment]
> What AppID are you using? I can't replicate this with `440` (Team Fortress 2).

730

**Comment by garhow** [comment]
Getting the raw JSON data for 730 from https://api.steampowered.com/ISteamEconomy/GetAssetPrices/v1/?appid=730 shows that there are no tags fields in the result, so we should make them optional.

**Comment by garhow** [comment]
Seems to be fixed in df57cc52d1589e539388d582ed6d0d2c8d5e4178.
